/**
 * Agent Documentation Generator
 * Generates a comprehensive agent.md file that helps AI assistants 
 * understand the entire project structure, tools, and capabilities.
 */

const fs = require('fs');
const path = require('path');

class AgentDocGenerator {
  constructor(projectRoot) {
    this.projectRoot = projectRoot;
    this.skipDirs = ['node_modules', '.git', 'dist', 'build', '.vscode'];
    this.maxFileSize = 50 * 1024; // 50KB max per file for docs
  }

  /**
   * Generate comprehensive agent.md documentation
   */
  async generateAgentDoc() {
    const doc = [];
    
    // Header
    doc.push('# 🤖 Cuckoo Code - Agent Knowledge Base\n');
    doc.push('> **Purpose**: This document provides AI assistants with complete context about the Cuckoo Code project, enabling them to understand, modify, and extend the codebase effectively.\n');
    doc.push('---\n');
    
    // Quick Start for Agents
    doc.push('## 🚀 Quick Start for AI Agents\n');
    doc.push(this.generateQuickStart());
    
    // Project Overview
    doc.push('\n---\n');
    doc.push('## 📋 Project Overview\n');
    doc.push('Cuckoo Code is an AI-powered code assistant that can read, edit, search files, execute commands, and interact with databases and web APIs. It provides a secure sandboxed environment for AI agents to perform coding tasks.\n');
    
    // Project Structure
    doc.push('\n---\n');
    doc.push('## 📁 Project Structure\n');
    doc.push(this.generateProjectStructure());
    
    // Core Files Description
    doc.push('\n---\n');
    doc.push('## 📄 Core Files\n');
    doc.push(this.describeCoreFiles());
    
    // Tool System
    doc.push('\n---\n');
    doc.push('## 🔧 Tool System Architecture\n');
    doc.push(this.describeToolSystem());
    
    // Available Tools API
    doc.push('\n---\n');
    doc.push('## 🛠️ Available Tools API Reference\n');
    doc.push(this.generateToolAPI());
    
    // Usage Patterns
    doc.push('\n---\n');
    doc.push('## 💡 Usage Patterns & Examples\n');
    doc.push(this.generateUsagePatterns());
    
    // Interaction Workflow
    doc.push('\n---\n');
    doc.push('## 🔄 Agent Interaction Workflow\n');
    doc.push(this.generateWorkflow());
    
    // Rules and Constraints
    doc.push('\n---\n');
    doc.push('## ⚠️ Rules and Constraints\n');
    doc.push(this.generateRules());
    
    // Common Tasks
    doc.push('\n---\n');
    doc.push('## ✅ Common Task Examples\n');
    doc.push(this.generateCommonTasks());
    
    // Footer
    doc.push('\n---\n');
    doc.push('*Generated by AgentDocGenerator - Keep this file updated when project structure changes*\n');
    
    return doc.join('\n');
  }

  /**
   * Generate quick start section
   */
  generateQuickStart() {
    return `### How to Use This Document

1. **Read this entire document first** to understand the project capabilities
2. **Wait for user commands** via chat interface (e.g., "Add authentication", "Fix bug in X")
3. **Analyze before acting**: Read relevant files using \`readFile()\`, \`glob()\`, or \`grep()\`
4. **Present a plan**: Explain what files you'll modify and what changes you'll make
5. **Wait for confirmation** from the user before making any changes
6. **Execute changes** using precise tool calls (\`editFile()\`, \`writeFile()\`, etc.)
7. **Verify and report**: Confirm changes work and summarize what was done

### Key Principle
> **Always read before writing. Never assume. Always confirm before modifying.**`;
  }

  /**
   * Generate project structure tree
   */
  generateProjectStructure() {
    const structure = [];
    const rootItems = fs.readdirSync(this.projectRoot).filter(item => {
      return !this.skipDirs.includes(item) && !item.startsWith('.');
    });

    structure.push('```\n/workspace/');
    
    for (const item of rootItems.sort()) {
      const fullPath = path.join(this.projectRoot, item);
      const stat = fs.statSync(fullPath);
      
      if (stat.isDirectory()) {
        structure.push(`├── ${item}/`);
        // List first level of subdirectory
        try {
          const subItems = fs.readdirSync(fullPath).slice(0, 5);
          for (const sub of subItems) {
            if (!sub.startsWith('.')) {
              structure.push(`│   ├── ${sub}`);
            }
          }
        } catch (e) {
          // Skip if can't read
        }
      } else {
        structure.push(`├── ${item}`);
      }
    }
    
    structure.push('```\n');
    return structure.join('\n');
  }

  /**
   * Describe core files
   */
  describeCoreFiles() {
    const coreFiles = [
      { name: 'main.js', desc: 'Electron main process - handles window creation, IPC communication' },
      { name: 'preload.js', desc: 'Preload script - exposes secure API to renderer process' },
      { name: 'systemPrompt.md', desc: 'System prompt defining AI behavior, tool usage rules, and coding guidelines' },
      { name: 'README.md', desc: 'Project documentation and usage instructions' },
      { name: 'package.json', desc: 'Project configuration, dependencies, and build scripts' }
    ];

    const lines = [];
    for (const file of coreFiles) {
      const filePath = path.join(this.projectRoot, file.name);
      if (fs.existsSync(filePath)) {
        lines.push(`- **${file.name}**: ${file.desc}`);
      }
    }
    return lines.join('\n');
  }

  /**
   * Describe tool system architecture
   */
  describeToolSystem() {
    return `The tool system consists of:
- **ToolRegistry**: Central registry for all available tools
- **UnifiedToolManager**: Manages tool execution and lifecycle
- **ToolBridge**: Bridges between AI requests and tool implementations
- **Individual Tools**: Specialized tools for specific operations

Tools are organized in the \`/tools/\` directory and follow a consistent interface.`;
  }

  /**
   * Generate tool API documentation
   */
  generateToolAPI() {
    const tools = [
      {
        name: 'readFile',
        signature: 'readFile(filePath: string, encoding?: string): Promise<string>',
        desc: 'Read file content. Returns first 1MB if larger.'
      },
      {
        name: 'readFileWithLines',
        signature: 'readFileWithLines(filePath: string, encoding?: string): Promise<string>',
        desc: 'Read file with line numbers prefixed (format: "line: content")'
      },
      {
        name: 'writeFile',
        signature: 'writeFile(filePath: string, content: string, encoding?: string): Promise<FileWriteResult>',
        desc: 'Create or overwrite file. Auto-creates parent directories.'
      },
      {
        name: 'editFile',
        signature: 'editFile(filePath: string, oldString: string, newString: string, replaceAll?: boolean): Promise<FileEditResult>',
        desc: 'Precise string replacement in files. Requires exact match.'
      },
      {
        name: 'deleteFile',
        signature: 'deleteFile(filePath: string): Promise<FileDeleteResult>',
        desc: 'Delete a file permanently. Cannot delete directories.'
      },
      {
        name: 'glob',
        signature: 'glob(pattern: string, searchPath?: string): Promise<string[]>',
        desc: 'Search files by glob pattern. Skips node_modules, .git, dist.'
      },
      {
        name: 'grep',
        signature: 'grep(pattern: string, options?: GrepOptions): Promise<GrepResult>',
        desc: 'Search content by regex/text. Returns matches with line numbers.'
      },
      {
        name: 'bash',
        signature: 'bash(command: string, options?: BashOptions): Promise<BashResult>',
        desc: 'Execute shell commands. Does not throw on failure - check exitCode.'
      },
      {
        name: 'mysql',
        signature: 'mysql(options: MysqlOptions): Promise<MysqlResult>',
        desc: 'Execute MySQL queries. Supports parameterized queries.'
      },
      {
        name: 'webFetch',
        signature: 'webFetch(url: string, options?: WebFetchOptions): Promise<WebFetchResult>',
        desc: 'Fetch HTTP/HTTPS URLs. Returns structured response.'
      },
      {
        name: 'log',
        signature: 'log(...args: unknown[]): void',
        desc: 'Output intermediate results to execution log.'
      }
    ];

    const lines = ['Available tools (all functions are async, use await):', ''];
    for (const tool of tools) {
      lines.push(`### ${tool.name}`);
      lines.push(`\`\`\`typescript`);
      lines.push(tool.signature);
      lines.push(`\`\`\``);
      lines.push(`${tool.desc}\n`);
    }
    return lines.join('\n');
  }

  /**
   * Generate usage patterns
   */
  generateUsagePatterns() {
    return `## Common Patterns

### Reading and Understanding Code
\`\`\`javascript
// Read a file to understand its content
const content = await readFile('src/main.js');

// Read with line numbers for precise discussion
const linedContent = await readFileWithLines('src/utils/helper.js');
\`\`\`

### Making Surgical Edits
\`\`\`javascript
// Edit with exact string matching
await editFile('src/app.js', 
  'old function code here',
  'new function code here'
);
\`\`\`

### Searching the Codebase
\`\`\`javascript
// Find all JS files in src
const jsFiles = await glob('**/*.js', 'src');

// Search for specific pattern
const matches = await grep('console\\.log', { ignoreCase: false });
\`\`\`

### Executing Commands
\`\`\`javascript
// Run npm install
const result = await bash('npm install');
if (result.exitCode !== 0) {
  log('Install failed:', result.stderr);
}
\`\`\`

### Database Operations
\`\`\`javascript
// Query MySQL
const result = await mysql({
  host: 'localhost',
  user: 'root',
  password: 'password',
  database: 'mydb',
  query: 'SELECT * FROM users WHERE id = ?',
  params: [123]
});
\`\`\``;
  }

  /**
   * Generate interaction workflow
   */
  generateWorkflow() {
    return `## Agent Workflow

1. **Initialize**: Read agent.md to understand project context
2. **Receive Command**: Wait for user instruction (e.g., "Add user authentication")
3. **Analyze**: 
   - Read relevant files using readFile/glob/grep
   - Understand current implementation
   - Identify required changes
4. **Plan**: Present a clear plan:
   - What files will be modified
   - What changes will be made
   - Any risks or considerations
5. **Confirm**: Ask user for approval before making changes
6. **Execute**: 
   - Make surgical edits using editFile/writeFile
   - Run tests or commands if needed
   - Verify changes work correctly
7. **Report**: Summarize what was done and any next steps

### Key Principles
- Always read before writing
- Make minimal, precise changes
- Ask clarifying questions when requirements are unclear
- Never assume - verify assumptions by reading code
- Test changes when possible`;
  }

  /**
   * Generate rules and constraints
   */
  generateRules() {
    return `## Rules and Constraints

### Safety Rules
- Do not execute dangerous commands (format, shutdown, taskkill, diskpart, reg delete)
- Do not modify files outside project directory
- Do not delete files without explicit user request
- Always backup important data before major changes

### Coding Standards
- Prefer simple solutions over complex ones
- Avoid over-engineering or premature optimization
- Write readable, maintainable code
- Follow existing code style and patterns

### Modification Guidelines
- Make surgical, targeted changes
- Do not reformat or refactor unrelated code
- Each edit should have a single clear purpose
- Verify oldString uniqueness before editing

### Communication
- Be concise and professional
- Show code and command output directly
- For multi-step tasks, present plan first
- Ask questions when requirements are ambiguous
- Explain how changes solve the problem`;
  }

  /**
   * Generate common task examples
   */
  generateCommonTasks() {
    return `### Task 1: Add User Authentication

**User Request**: "Add JWT authentication to the login system"

**Agent Steps**:
1. Read current auth implementation: \`await readFile('src/auth/login.js')\`
2. Search for related files: \`await glob('**/*auth*.js')\`
3. Present plan: "I will modify X, Y, Z files to add JWT..."
4. Wait for user confirmation
5. Execute: \`await editFile(...)\` for each file
6. Test: \`await bash('npm test')\`
7. Report: "Authentication added. Files modified: ..."

### Task 2: Fix a Bug

**User Request**: "The app crashes when deleting empty files"

**Agent Steps**:
1. Search for delete logic: \`await grep('deleteFile', { path: 'tools' })\`
2. Read the FileDeleteTool: \`await readFile('tools/FileDeleteTool.js')\`
3. Identify the bug (e.g., no empty check)
4. Present fix plan with code snippet
5. After confirmation, apply: \`await editFile('tools/FileDeleteTool.js', ...)\`
6. Verify fix works

### Task 3: Add New Feature

**User Request**: "Add support for PostgreSQL database"

**Agent Steps**:
1. Read existing MySQL tool: \`await readFile('tools/MySQLTool.js')\`
2. Understand the tool interface pattern
3. Create new PostgresTool following same pattern
4. Register in ToolRegistry
5. Update documentation
6. Present all changes for review before committing

### Task 4: Refactor Code

**User Request**: "Improve error handling in file operations"

**Agent Steps**:
1. Analyze current error handling: \`await grep('try\\s*{', { path: 'tools' })\`
2. Identify files needing improvement
3. Propose standardized error handling pattern
4. Apply changes one file at a time
5. Test each change before moving to next`;
  }
}

module.exports = { AgentDocGenerator };
